name: CI testing

on:

push:

branches:

- main

jobs:

test:

    runs-on: ubuntu-latest

    name: Run ESLint and JEST test

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint 

    - run: npm run test